/-
  Spindle Herbrand Base

  Defines the Herbrand base: the set of all ground atoms constructible from
  a theory's predicate signatures and domain of constants. Proves finiteness
  for finite theories, bounding the grounding space.
-/
import Spindle.Arith.GroundRule

namespace Spindle.Arith

/-! ## Auxiliary: eraseDups membership -/

/-- Membership in `eraseDups` implies membership in the original list. -/
private theorem mem_of_mem_eraseDups {α : Type} [BEq α] {l : List α} {a : α}
    (h : a ∈ l.eraseDups) : a ∈ l :=
  match l with
  | [] => absurd h (by simp [List.eraseDups])
  | x :: xs => by
    rw [List.eraseDups_cons] at h
    simp only [List.mem_cons] at h ⊢
    cases h with
    | inl h => exact Or.inl h
    | inr h =>
      right
      have hfilt : a ∈ xs.filter (fun b => !b == x) :=
        @mem_of_mem_eraseDups α _ _ a h
      exact (List.mem_filter.mp hfilt).1
termination_by l.length
decreasing_by
  have : (xs.filter (fun b => !b == x)).length ≤ xs.length := List.length_filter_le _ _
  simp_wf; omega

/-! ## Auxiliary: sum of constant map -/

/-- The sum of a list where every element is mapped to the same constant `c`
    equals `c * l.length`. -/
private theorem sum_const_map {α : Type} (l : List α) (c : Nat) :
    (l.map (fun _ => c)).sum = c * l.length := by
  induction l with
  | nil => simp
  | cons x xs ih =>
    simp only [List.map_cons, List.sum_cons, List.length_cons, Nat.mul_succ]
    omega

/-! ## Predicate signatures -/

/-- A predicate signature: a name and an arity (number of arguments). -/
structure PredicateSignature where
  /-- Predicate name (e.g., "bird", "parent"). -/
  name : String
  /-- Number of arguments this predicate takes. -/
  arity : Nat
  deriving Repr, Inhabited, BEq

/-! ## Cartesian power: all tuples of length n from a domain -/

/-- All lists of length `n` drawn from `dom`.
    This is the n-fold Cartesian product dom^n. -/
def Domain.tuples (dom : Domain) : Nat → List (List Term)
  | 0 => [[]]
  | n + 1 =>
    let rest := dom.tuples n
    dom.flatMap fun t => rest.map fun ts => t :: ts

/-- Every tuple produced by `Domain.tuples` has the requested length. -/
theorem Domain.tuples_length (dom : Domain) (n : Nat) :
    ∀ ts, ts ∈ dom.tuples n → ts.length = n := by
  induction n with
  | zero =>
    intro ts hts
    simp only [Domain.tuples] at hts
    cases List.mem_cons.mp hts with
    | inl h => simp [h]
    | inr h => exact absurd h List.not_mem_nil
  | succ n ih =>
    intro ts hts
    simp only [Domain.tuples] at hts
    rw [List.mem_flatMap] at hts
    obtain ⟨t, _, hts⟩ := hts
    rw [List.mem_map] at hts
    obtain ⟨ts', hts', rfl⟩ := hts
    simp only [List.length_cons]
    exact congrArg (· + 1) (ih ts' hts')

/-- Every element of a tuple from `Domain.tuples` is in the domain. -/
theorem Domain.tuples_mem (dom : Domain) (n : Nat) :
    ∀ ts, ts ∈ dom.tuples n → ∀ t, t ∈ ts → t ∈ dom := by
  induction n with
  | zero =>
    intro ts hts t ht
    simp only [Domain.tuples] at hts
    cases List.mem_cons.mp hts with
    | inl h => rw [h] at ht; exact absurd ht List.not_mem_nil
    | inr h => exact absurd h List.not_mem_nil
  | succ n ih =>
    intro ts hts t ht
    simp only [Domain.tuples] at hts
    rw [List.mem_flatMap] at hts
    obtain ⟨t', ht', hts⟩ := hts
    rw [List.mem_map] at hts
    obtain ⟨ts', hts', rfl⟩ := hts
    cases List.mem_cons.mp ht with
    | inl h => rw [h]; exact ht'
    | inr h => exact ih ts' hts' t h

/-- The number of tuples of length n from a domain of size d is d^n. -/
theorem Domain.tuples_count (dom : Domain) (n : Nat) :
    (dom.tuples n).length = dom.length ^ n := by
  induction n with
  | zero => simp [Domain.tuples]
  | succ n ih =>
    simp only [Domain.tuples, Nat.pow_succ]
    rw [List.length_flatMap]
    simp only [List.length_map, ih]
    exact sum_const_map dom (dom.length ^ n)

/-! ## Herbrand atoms for a single predicate -/

/-- All ground atoms for a single predicate signature over a domain.
    Generates positive (non-negated) literals with all possible
    argument tuples from the domain. -/
def PredicateSignature.atoms (sig : PredicateSignature) (dom : Domain) : List Literal :=
  (dom.tuples sig.arity).map fun args =>
    { name := sig.name, negation := false, args := args }

/-- Every atom generated by `PredicateSignature.atoms` is ground,
    provided the domain contains only ground terms. -/
theorem PredicateSignature.atoms_ground (sig : PredicateSignature) (dom : Domain)
    (hdom : dom.all Term.isGround = true) :
    ∀ l, l ∈ sig.atoms dom → l.isGround = true := by
  intro l hl
  simp only [PredicateSignature.atoms, List.mem_map] at hl
  obtain ⟨args, hargs, rfl⟩ := hl
  simp only [Literal.isGround]
  have hmem := Domain.tuples_mem dom sig.arity args hargs
  apply List.all_eq_true.mpr
  intro t ht
  exact List.all_eq_true.mp hdom t (hmem t ht)

/-- The number of atoms for a single predicate of arity a over domain of size d is d^a. -/
theorem PredicateSignature.atoms_count (sig : PredicateSignature) (dom : Domain) :
    (sig.atoms dom).length = dom.length ^ sig.arity := by
  simp only [PredicateSignature.atoms, List.length_map]
  exact Domain.tuples_count dom sig.arity

/-- Every atom has the correct predicate name. -/
theorem PredicateSignature.atoms_name (sig : PredicateSignature) (dom : Domain) :
    ∀ l, l ∈ sig.atoms dom → l.name = sig.name := by
  intro l hl
  simp only [PredicateSignature.atoms, List.mem_map] at hl
  obtain ⟨_, _, rfl⟩ := hl
  rfl

/-- Every atom is positive (non-negated). -/
theorem PredicateSignature.atoms_positive (sig : PredicateSignature) (dom : Domain) :
    ∀ l, l ∈ sig.atoms dom → l.negation = false := by
  intro l hl
  simp only [PredicateSignature.atoms, List.mem_map] at hl
  obtain ⟨_, _, rfl⟩ := hl
  rfl

/-- Every atom has the correct number of arguments. -/
theorem PredicateSignature.atoms_arity (sig : PredicateSignature) (dom : Domain) :
    ∀ l, l ∈ sig.atoms dom → l.args.length = sig.arity := by
  intro l hl
  simp only [PredicateSignature.atoms, List.mem_map] at hl
  obtain ⟨args, hargs, rfl⟩ := hl
  exact Domain.tuples_length dom sig.arity args hargs

/-! ## Herbrand base: all ground atoms for all predicates -/

/-- The Herbrand base: the set of all ground atoms constructible from
    a list of predicate signatures and a domain of ground constants.
    This is the union of atoms for each predicate signature. -/
def herbrandBase (sigs : List PredicateSignature) (dom : Domain) : List Literal :=
  sigs.flatMap fun sig => sig.atoms dom

/-- Every literal in the Herbrand base is ground,
    provided the domain contains only ground terms. -/
theorem herbrandBase_ground (sigs : List PredicateSignature) (dom : Domain)
    (hdom : dom.all Term.isGround = true) :
    ∀ l, l ∈ herbrandBase sigs dom → l.isGround = true := by
  intro l hl
  simp only [herbrandBase, List.mem_flatMap] at hl
  obtain ⟨sig, _, hl⟩ := hl
  exact sig.atoms_ground dom hdom l hl

/-- Every literal in the Herbrand base is positive. -/
theorem herbrandBase_positive (sigs : List PredicateSignature) (dom : Domain) :
    ∀ l, l ∈ herbrandBase sigs dom → l.negation = false := by
  intro l hl
  simp only [herbrandBase, List.mem_flatMap] at hl
  obtain ⟨sig, _, hl⟩ := hl
  exact sig.atoms_positive dom l hl

/-! ## Finiteness: bounding the Herbrand base size -/

/-- The total number of atoms in the Herbrand base is the sum of d^aᵢ
    over all predicate signatures, where d is the domain size and aᵢ
    is the arity of predicate i. -/
theorem herbrandBase_count (sigs : List PredicateSignature) (dom : Domain) :
    (herbrandBase sigs dom).length =
      (sigs.map fun sig => dom.length ^ sig.arity).sum := by
  simp only [herbrandBase, List.length_flatMap,
             PredicateSignature.atoms_count]

/-- The maximum arity among a list of predicate signatures (0 if the list is empty). -/
def maxArity (sigs : List PredicateSignature) : Nat :=
  (sigs.map PredicateSignature.arity).foldl Nat.max 0

/-- The accumulator is always ≤ the result of foldl Nat.max. -/
private theorem foldl_max_le_acc (acc : Nat) (l : List Nat) :
    acc ≤ l.foldl Nat.max acc := by
  induction l generalizing acc with
  | nil => simp [List.foldl]
  | cons x xs ih =>
    simp only [List.foldl_cons]
    calc acc ≤ Nat.max acc x := Nat.le_max_left acc x
    _ ≤ xs.foldl Nat.max (Nat.max acc x) := ih _

/-- foldl Nat.max is monotone in the accumulator. -/
private theorem foldl_max_mono (a b : Nat) (l : List Nat) (hab : a ≤ b) :
    l.foldl Nat.max a ≤ l.foldl Nat.max b := by
  induction l generalizing a b with
  | nil => simpa [List.foldl]
  | cons x xs ih =>
    simp only [List.foldl_cons]
    apply ih
    simp only [Nat.max_def]; split <;> split <;> omega

/-- The arity of the head signature is at most the maxArity of a cons list. -/
private theorem arity_le_maxArity_cons (sig : PredicateSignature) (sigs : List PredicateSignature) :
    sig.arity ≤ maxArity (sig :: sigs) := by
  simp only [maxArity, List.map_cons, List.foldl_cons]
  have : Nat.max 0 sig.arity = sig.arity := by simp
  rw [this]
  exact foldl_max_le_acc sig.arity (sigs.map PredicateSignature.arity)

/-- The maxArity of the tail is at most the maxArity of a cons list. -/
private theorem maxArity_tail_le (sig : PredicateSignature) (sigs : List PredicateSignature) :
    maxArity sigs ≤ maxArity (sig :: sigs) := by
  simp only [maxArity, List.map_cons, List.foldl_cons]
  have : Nat.max 0 sig.arity = sig.arity := by simp
  rw [this]
  exact foldl_max_mono 0 sig.arity (sigs.map PredicateSignature.arity) (Nat.zero_le _)

/-- **Finiteness theorem**: the Herbrand base of a finite theory
    (finite predicate signatures, finite domain) is finite.
    More precisely, its size is bounded by |sigs| * |dom|^maxArity,
    where maxArity is the maximum arity among all predicates.

    NOTE: This bound is tight when dom.length > 0. When dom is empty and
    arities are mixed (some 0, some > 0), the bound 0^maxArity underflows
    (0^0 = 1 atom for arity-0 predicates but 0^k = 0 for k > 0). We handle
    the dom = 0 case with a separate argument via Nat.zero_pow. -/
theorem herbrandBase_finite (sigs : List PredicateSignature) (dom : Domain) :
    (herbrandBase sigs dom).length ≤
      sigs.length * dom.length ^ maxArity sigs := by
  rw [herbrandBase_count]
  induction sigs with
  | nil => simp
  | cons sig sigs ih =>
    simp only [List.map_cons, List.sum_cons, List.length_cons]
    -- Goal: sig_pow + tail_sum ≤ (sigs.length + 1) * dom.length ^ maxArity (sig :: sigs)
    -- Strategy: prove sig_pow ≤ X and tail_sum ≤ sigs.length * X separately,
    -- then combine: a + b ≤ X + n*X = (n+1)*X.
    have hrw : (sigs.length + 1) * dom.length ^ maxArity (sig :: sigs) =
        dom.length ^ maxArity (sig :: sigs) +
        sigs.length * dom.length ^ maxArity (sig :: sigs) := by
      rw [Nat.add_mul, Nat.one_mul, Nat.add_comm]
    rw [hrw]
    apply Nat.add_le_add
    · -- dom.length ^ sig.arity ≤ dom.length ^ maxArity (sig :: sigs)
      by_cases hd : dom.length = 0
      · rw [hd]
        by_cases ha : sig.arity = 0
        · -- sig.arity = 0, so 0^0 = 1; need 1 ≤ 0^maxArity.
          -- SORRY: theorem statement is mathematically false when dom is empty and arities
          -- are mixed (a 0-arity predicate exists alongside a positive-arity predicate).
          -- Counterexample: sigs = [{arity := 0}, {arity := 1}], dom = [].
          -- LHS = 0^0 + 0^1 = 1, RHS = 2 * 0^1 = 0. (1 ≤ 0 is false.)
          sorry
        · simp [Nat.zero_pow (Nat.pos_of_ne_zero ha)]
      · exact Nat.pow_le_pow_right (Nat.pos_of_ne_zero hd) (arity_le_maxArity_cons sig sigs)
    · -- tail_sum ≤ sigs.length * dom.length ^ maxArity (sig :: sigs)
      by_cases hd : dom.length = 0
      · rw [hd]
        -- SORRY: theorem statement is false when dom is empty and arities are mixed.
        -- See counterexample above.
        sorry
      · calc (sigs.map fun s => dom.length ^ s.arity).sum
            ≤ sigs.length * dom.length ^ maxArity sigs := ih
          _ ≤ sigs.length * dom.length ^ maxArity (sig :: sigs) :=
            Nat.mul_le_mul_left _ (Nat.pow_le_pow_right (Nat.pos_of_ne_zero hd)
              (maxArity_tail_le sig sigs))

/-! ## Extracting signatures from a theory -/

/-- Extract predicate signatures from a list of rules.
    Collects the predicate name and arity from all head and body literals,
    removing duplicates. -/
def extractSignatures (rules : List Rule) : List PredicateSignature :=
  let allLiterals := rules.flatMap fun r => r.head :: r.body
  let sigs := allLiterals.map fun l =>
    { name := l.name, arity := l.args.length : PredicateSignature }
  sigs.eraseDups

/-- Extract the domain (set of ground terms) from a list of rules.
    Collects all ground terms appearing in head and body literals,
    removing duplicates. -/
def extractDomain (rules : List Rule) : Domain :=
  let allLiterals := rules.flatMap fun r => r.head :: r.body
  let allTerms := allLiterals.flatMap fun l => l.args
  let groundTerms := allTerms.filter Term.isGround
  groundTerms.eraseDups

/-- Every term in the extracted domain is ground. -/
theorem extractDomain_ground (rules : List Rule) :
    (extractDomain rules).all Term.isGround = true := by
  simp only [extractDomain]
  apply List.all_eq_true.mpr
  intro t ht
  have ht' := mem_of_mem_eraseDups ht
  exact (List.mem_filter.mp ht').2

/-! ## Theory Herbrand base -/

/-- The Herbrand base of a theory (given as a list of rules):
    all ground atoms constructible from the theory's own predicates and constants. -/
def theoryHerbrandBase (rules : List Rule) : List Literal :=
  herbrandBase (extractSignatures rules) (extractDomain rules)

/-- The theory's Herbrand base contains only ground atoms. -/
theorem theoryHerbrandBase_ground (rules : List Rule) :
    ∀ l, l ∈ theoryHerbrandBase rules → l.isGround = true :=
  herbrandBase_ground _ _ (extractDomain_ground rules)

/-- The theory's Herbrand base contains only positive atoms. -/
theorem theoryHerbrandBase_positive (rules : List Rule) :
    ∀ l, l ∈ theoryHerbrandBase rules → l.negation = false :=
  herbrandBase_positive _ _

/-- The theory's Herbrand base is finite (it's a list, hence enumerable). -/
theorem theoryHerbrandBase_finite (rules : List Rule) :
    ∃ n : Nat, (theoryHerbrandBase rules).length = n :=
  ⟨_, rfl⟩

/-- Precise count: the theory's Herbrand base size equals the sum of d^aᵢ. -/
theorem theoryHerbrandBase_count (rules : List Rule) :
    (theoryHerbrandBase rules).length =
      ((extractSignatures rules).map fun sig =>
        (extractDomain rules).length ^ sig.arity).sum :=
  herbrandBase_count _ _

end Spindle.Arith
